### ISSUE TITLE
Change Filename to video ID

### ISSUE THREAD

**Issue by Obika1871** [Tairraos/TikDown#22]
Hi, first of all, let me thank you for this amazing tool. It is the only one I have seen so far that is able to download an entire account without missing a single video and without watermark.

I just have one issue with it : the files downloaded don't have the video ID in the filename. This is important to me because every other tool I have used so far puts the video ID in the filename (sometimes they add stuff like "Date-VideoID" or "AccountName-VideoID" but that's easy to rename en masse). This means that videos downloaded with your tool would be really hard to organize in the long term.

To be clear with what I mean by "video ID", for example : with this url https://www.tiktok.com/@natgeo/video/7203786116573498666 , the video ID would be 7203786116573498666 .

I know that in the "Features to be implemented" you wrote "Allow user to select filename template". This would be a really awesome addition. Do you have an estimate for when you might add this in a release ?

If this isn't planned to be released soon, could you walk me through how to edit the code to include the video ID in the filename ?
I imagine it has to do with the highlighted line in this screenshot, but my coding skills are very poor and I didn't manage to edit in any way that didn't breaking the program.
![filename](https://user-images.githubusercontent.com/123712415/221682290-7b050200-a951-482b-948f-ad234dbbc8f1.PNG)

Again, thank you so much for this program. And thank you for the english translations. Your english is much better than my chinese would be so I sticked to it to ask you for help :)

**Comment by Tairraos** [comment]
Sorry for I have no planned to update app soon later. Since I have no idea how to design UI to setup template string yet. If you'd like to edit code and build one version for yourself, let me show you how to make it.

Grab one more data from server return: "id: rootInfo["aweme_id"],"
![image](https://user-images.githubusercontent.com/185069/221712287-061a861f-b789-4023-a836-9aba348ee342.png)

Then, you can use id replace the date to id or some another template you can customize it.
![image](https://user-images.githubusercontent.com/185069/221711706-0fa73bc8-0115-4eb0-853e-c468a5ff8f94.png)

First:
```shell
git clone https://github.com/Tairraos/TikDown.git
cd TikDown
npm i
```

then edit the code, and debug it.
```shell
npm start #debug code
npm run build:win #build windows package on x64 win
npm run build:mac #build mac package
```

**Comment by Obika1871** [comment]
That worked ! Thank you very much !
